version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        steps:
            - checkout
            - run: npm install
            - run: npm install htmlhint
            - run: npm install jslint
            - run: npm install csslint
    test:
        docker:
            - image: circleci/node:10.16.0
            steps:
            - run: ./node_modules/htmlhint/bin/htmlhint
            - run: ./node_modules/.bin/jslint
            - run: ./node_modules/.bin/csslint
            - run: mkdir -p my_workspace
            - run: echo "Trying out workspaces" > my_workspace/echo-output
            - persist_to_workspace:
                root: my_workspace
                paths:
                        - echo-output
workflows:
    version: 2
    running_job:
        jobs:
        - build
        - test
